CREATE TABLE student (
	ID NUMBER(8),
	NAME VARCHAR2(100),
	MAJOR VARCHAR2(200),
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER IN('M', 'W')),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);

SELECT * FROM STUDENT;

INSERT INTO STUDENT (ID, NAME, MAJOR, BIRTH)
VALUES (1, '한동석', '경영학과', TO_DATE('1981-12-04', 'YYYY-MM-DD'));


-- DML


--PLAYER테이블에서 TEAM_ID가 'K01'인 선수 검색

SELECT * FROM PLAYER WHERE TEAM_ID = 'K01';

--PLAYER 테이블에서 TEAM_ID가 'K01'이 아닌 선수 검색
SELECT * FROM PLAYER WHERE TEAM_ID != 'K01';

--PLAYER 테이블에서 WEIGHT가 70 이상이고 80 이하인 선수 검색
SELECT * FROM PLAYER WHERE WEIGHT >= 70 AND WEIGHT <=80;

--PLAYER 테이블에서 TEAM_ID가 'K06'이고 NICKNAME이 '제리'인 선수 검색

SELECT * FROM PLAYER WHERE TEAM_ID = 'K06' AND NICKNAME = '제리';

--PLAYER테이블에서 HEIGHT가 170 이상이고 WEIGHT가 80이상인 선수 이름 검색
SELECT PLAYER_NAME FROM PLAYER WHERE HEIGHT >=170 AND WEIGHT >= 80;

--STADIUM 테이블에서 SEAT_COUNT가 30000초과이고 41000이하인 경기장 검색
SELECT * FROM STADIUM WHERE SEAT_COUNT > 30000 AND SEAT_COUNT <= 41000;

--PLAYER 테이블에서 TEAM_ID가 'K02'이거나 'K07'이고 포지션은 'MF'인 선수 검색
SELECT * FROM PLAYER WHERE POSITION = 'MF' 

--CASE문 사용
--STADIUM 테이블에서 SEAT_COUNT가 0 이상 30000이하면 'S' 30001이상 50000이하면 'M' 다 아니면 'L'
SELECT STADIUM_ID,
CASE 
	WHEN (S.SEAT_COUNT BETWEEN 0 AND 30000) THEN 'S'
	WHEN (S.SEAT_COUNT BETWEEN 300001 AND 50000) THEN 'M'
	ELSE 'L'
END AS STADIUM_SIZE
FROM STADIUM S;

--EMPLOYEES 테이블에서 평균보다 낮은 사람들의 급여 10% 인상하기
SELECT * FROM EMPLOYEES;

SELECT 





