CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000;

CREATE TABLE USER_TBL( 
	USER_NUMBER NUMBER NOT NULL,
	ID VARCHAR2(100),
	PW VARCHAR2(100),
	NAME VARCHAR2(100),
	AGE NUMBER,
	PHONENUMBER VARCHAR2(15),
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);

SELECT * FROM USER_TBL;

