CREATE TABLE BOARD (
	SEQ INT GENERATED ALWAYS AS IDENTIFY PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	CONTENT VARCHAR(1000) NOT NULL,
	WRITER VARCHAR(10) NOT NULL,
	PASSWORD INT NOT NULL,
	REGDATE TIMESTAMP NOT NULL,
	CNT INT NOT NULL
);